config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tasks
  root 'tasks#index', as: :root
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  validates_presence_of :title, :description
  validates_uniqueness_of :title
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :rememberable
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[show edit update destroy]
  
  def index
    @tasks = Task.all
  end
  
  def new
    @task = Task.new
  end

  def create
    @task = current_user.tasks.new(task_params)
    respond_to do |format|
      if @task.save
        format.html { redirect_to tasks_path, notice: 'Task was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end
  
  def update
    @task.update(task_params)
  end
  
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end
  
  def task_params
    params.require(:task).permit(:title, :description, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-dark bg-inverse">
  <%= link_to root_path, class: 'navbar-brand' do -%>
    <h2>TO-DO SAGE</h2>
  <% end -%>
  <ul class="nav navbar-nav">
    <li class="nav-item active">
      <% if user_signed_in? -%>
          <%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: 'btn btn-outline-success' %>
      <% else -%>
          <%= link_to 'Log In', new_user_session_path, class: 'btn btn-outline-success' %>
      <% end -%>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDoSage</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'layouts/header' %>
    <div class="container">
      <% unless notice.blank? -%>
          <div class="alert alert-info alert-dismissable">
            <%= link_to '#', class: 'close', data: { dismiss: :alert } do -%>
                &times;
            <% end -%>
            <p id="notice"><%= notice %></p>
          </div>
      <% end -%>
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="row">
  <div class="col-md-4">
    <%= form_for(task) do |f| %>
        <% if task.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(task.errors.count, 'error') %> prohibited this task from being saved:</h2>
              <ul>
                <% task.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
              </ul>
            </div>
        <% end %>
        <fieldset>
          <div class="form-group">
            <%= f.text_field :title, placeholder: 'Title', class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.text_area :description,  placeholder: 'Description', class: 'form-control' %>
          </div>
          <%= f.submit 'Create task', class: 'btn btn-success' %>
        </fieldset>
    <% end %>
  </div>
</div>

app/views/tasks/_task.html.erb
<div class="card">
  <strong> <%= task.title %></strong>
  <small> <%= link_to :delete, task_path(task), method: :delete %></small><br>
  <p><%= task.description %></p>
  <%= form_for task, url: "/tasks/#{task.id}", method: :patch do |f| %>
    <small><%= f.label(:completed) %></small>
    <%= f.check_box :completed %>
  <% end -%>
  <small>
    <%= "Last update: #{time_ago_in_words(task.updated_at)} ago" %>
  </small>
</div>

app/views/tasks/index.html.erb
<div class="tasks-container">
  <%= render @tasks %>
</div>
<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>